spring.application.name=TieuLuanChuyenNganhFITHCMUTE

# ========== SQL Server ==========
spring.datasource.url=jdbc:sqlserver://localhost:1434;databaseName=QuanLyTruongHocTLCN;encrypt=true;trustServerCertificate=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=sa
spring.datasource.password=12345678
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.use_nationalized_character_data=true
# ========== JPA / Hibernate ==========
# none  = không đụng cấu trúc bảng (dùng khi đã tạo bảng bằng script)
# update = Hibernate tự tạo/sửa bảng theo Entity

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=true

# ========== Application Port ==========
server.port=8082

# ========== Thymeleaf ==========
spring.thymeleaf.cache=false

# ========== Internationalization (i18n) ==========
spring.messages.basename=messages/messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false

# ========== Logging ==========
logging.level.root=INFO
logging.level.vn.TieuLuanChuyenNganhFITHCMUTE=DEBUG
#logging.level.org.springframework.security=DEBUG